### ISSUE TITLE
Questions about approximate search

### ISSUE THREAD

**Issue by BaileyTrotter** [roedoejet/mtd-starter#14]
Hi Aidan, 

I set up the approximate search for my starter and it seems to be working okay. The main issues I'm noticing are:

1) It doesn't seem to be recognizing canonically equivalent unicode characters as equivalent, even though I see there's a NFC command in the .yaml file. All of the characters with diacritics in the data file are currently in the base character + separate combining diacritic form (ex. á U+0061/U+0301). If I search for entries using the single character instead (á U+00E1) I'm not getting results. Is there a way to fix this, other than manually adding each pair of equivalent characters to the approximate search file? I already did it manually for é U+00E9, and é U+0065/U+0301 as a test, but if I can avoid the manual approach for the characters with more than one diacritic that would be ideal.

2) The approximate search doesn't seem to be able to handle multiple errors in one word. I set up the approximate search to recognize that é U+00E9 and é U+0065/U+0301 should be the same character but it still doesn't seem to work if I search for a word with two of that character ex. the entry _mékʼénʼ_. Ideally I would be able to search for that word using _meken_, as well as _mékén_ (with U+00E9 instead of U+0065/U+0301) etc. Is this possible?

Thank you!

-Bailey

**Comment by roedoejet** [comment]
Hi Bailey,

Thanks for this. Yes, so the approx transducer actually is just creating another form in the list of data objects that make up your dictionary. It applies the rules that you define in that transducer and creates a "compare form" (`compare_form` in each entry in the dictionary data array). You can read a bit more about this [in section 5.3 here](https://aclanthology.org/W17-0119.pdf). With that in mind:

1. I can see that NFC is getting applied when creating the `compare_form` - have a look at your dictionary data here: https://github.com/BaileyTrotter/mtd-starter/blob/gh-pages/dict_cached.js - but, the _query_ is not getting converted. Unfortunately this isn't configurable, so there are two things you can do:
   - You can create a "norm.yaml" transducer. This is namespaced and will be applied to the _query_ (see the source here: https://github.com/roedoejet/mothertongues-UI/blob/master/src/assets/js/mtd.js). It's not documented I don't think yet, so you didn't miss anything! So, just to clarify, create a norm.csv and norm.yaml file in the `transducers` folder and configure with anything you want to apply to the query. You can then add this transducer in your data manifest, so it would look like this:
   
   ```"source": "word",
            "target": "compare_form",
            "functions": [
                "../transducers/norm.yaml",
                "../transducers/danish-approx.yaml"
            ]```

You could also just apply it to words like this:

          ```"source": "word",
            "target": "word",
            "functions": [
                "../transducers/norm.yaml",
            ]```
            


Unfortunately because of the way this works, you will have to list each transformation, so `\u0065\u0301,\u00E9` for example. If you want to actually apply an NFC normalization to the query, you could fork the [UI source](https://github.com/roedoejet/mothertongues-UI) and then change line 66 [here](https://github.com/roedoejet/mothertongues-UI/blob/master/src/pages/search/search.ts) to `let searchQuery = mtd.convertQuery(this.searchQuery).normalize('NFC')`; - then run `npm run-script minify` at the root to generate the minified source and commit the changes to `gh-pages`. Then point change line 31 in the [starter index.html](https://github.com/BaileyTrotter/mtd-starter/blob/gh-pages/index.html) to point to your version of the minified UI instead of mine. This is obviously more work, so just adding the norm transducer might be the best route unless you want to make more changes to the UI.
 
 2. The example you gave highlights the fact that there is only one "compare form" by default in mother tongues dictionaries, so you'd have to pick one approximate form per sound (it's meant as a heuristic, i.e. pick the most likely one). In your situation though, one of the approximate forms you give is just the NFC/NFD difference, which should get solved by implementing the `norm` transducer. Then, you could just keep the rule of `\u00E9,e` and let the `norm` transducer fix the normalization issues. That would be my recommendation given what I know from your post here.
 
 Let me know how this goes and if you have any more questions! Thanks @BaileyTrotter !

**Comment by BaileyTrotter** [comment]
Thank you @roedoejet! I'll work through these steps and see if any more questions come up.

**Comment by BaileyTrotter** [comment]
Hi @roedoejet, 

I’m revisIting this after a few months, and I have quite a few follow-up questions. 

1) What should the norm.yaml transducer file look like? Right now I structured it the same way as the approx.yaml file in the danish mtd-starter. But based on the description in the documentation, it sounds like it’s supposed to be used to create a composite mapping. 

2) What is the purpose of applying NFC normalization to the “compare_form”? The way I’ve been thinking about it, the dictionary has an entry for méddhin (me/U+0301ddhin). After the NFC normalization is applied there would then be two forms in the backend: me/U+0301ddhin and m/U+00E9ddhin. A user would then be able to get the result “méddhin” by entering either me/U+0301ddhin or m/U+00E9ddhin in the query. If this is how it works, I don’t understand why we need the norm.yaml transducer to apply to the query, and specify which characters should be treated as equivalent, since that is already being done in the compare_form.

3) Does Mother Tongues only allow one approximate form per sound (or even per entry)? We went through and identified multiple sounds which could be confused ex. in the case of méddhin, m is easily confused with n and md; é could be searched without the diacritic or confused with i, ae, ay; ddh is commonly confused with dh, d, th, or tth etc. Is it possible to account for all these possible query forms? 

4) I noticed both the mtd-starter and the web UI will give results which are a “Partial Match” or “Maybe you meant this?”. What is the difference between these two results?

5) You mentioned another solution which would allow the NFC to apply to the query was through forking the UI Source. Our plan is that once a working version of the dictionary is built using the mtd-starter, we will add the data to the Web-UI. Will NFC normalization already be applied to the query once we add data to the Web-UI? 

Let me know if any of these questions aren’t clear. As always, thank you so much for your help!

**Comment by roedoejet** [comment]
> Hi @roedoejet,
> 
> I’m revisIting this after a few months, and I have quite a few follow-up questions.
> 

Great! Sorry for the delay - the summer is always a bit hectic!

> 1. What should the norm.yaml transducer file look like? Right now I structured it the same way as the approx.yaml file in the danish mtd-starter. But based on the description in the documentation, it sounds like it’s supposed to be used to create a composite mapping.

You can create a composite mapping or it can just be a single mapping. Basically, the idea is that you want to normalize confusable characters into their proper codepoint. So, if you have a language that uses underlines, you might want to choose between U+0331 and U+0332 and include that in your normalization mapping. Sometimes it's convenient to separate different normalization mappings and combine them with a composite mapping - maybe you're building dictionaries for three languages and two of them use underlines and another two use apostrophes, so you might write mapping files for underline and apostrophe normalization separately and combine them in a composite mapping.

> 2. What is the purpose of applying NFC normalization to the “compare_form”? The way I’ve been thinking about it, the dictionary has an entry for méddhin (me/U+0301ddhin). After the NFC normalization is applied there would then be two forms in the backend: me/U+0301ddhin and m/U+00E9ddhin. A user would then be able to get the result “méddhin” by entering either me/U+0301ddhin or m/U+00E9ddhin in the query. If this is how it works, I don’t understand why we need the norm.yaml transducer to apply to the query, and specify which characters should be treated as equivalent, since that is already being done in the compare_form.

A few things here: I wouldn't include normalization equivalents in your compare_form transducer, so, you shouldn't have a rule that states `e\u0301,\u00E9` for example. You should have all of your forms using the same normalization (NFC is best if you can help it, since it renders more reliably in most browsers). So let's say you have the word `me/U+0301ddhin` in your dictionary, if you apply NFC normalization to both the word and the compare_form, you will get `m/U+00E9ddhin` for both - the backend will only have that representation (stored twice as the word and compare_form). Now, a possible rule for the compare form would be `\u00E9,e` since maybe people won't have the ability to type an accent or they won't hear the difference between an accented e or a unaccented e. So, if you apply that rule, now the backend will store the word as `m/U+00E9ddhin` and the compare form as `meddhin`. When a user makes a search, we don't know whether they will use the NFC or NFD variant, so it's important for us to normalize the query as well. That way, whether they search m/U+00E9ddhin or me/U+0301ddhin, they will both get normalized to m/U+00E9ddhin before the search is run on words and compare forms. Does that clear it up?

As an addendum to that, if you DIDN'T use NFC for the compare form, and you didn't convert e\u0301 to e (maybe everybody for this language just know's exactly how to spell it), you would still want to convert it to NFC because you're normalizing the query to NFC. If you didn't, the word would be m/U+00E9ddhin and the compare form would be me/U+0301ddhin and your query would always be normalized to m/U+00E9ddhin meaning the compare_form would always have an edit distance of 1 even when the user actually typed it in exactly.

> 3. Does Mother Tongues only allow one approximate form per sound (or even per entry)? We went through and identified multiple sounds which could be confused ex. in the case of méddhin, m is easily confused with n and md; é could be searched without the diacritic or confused with i, ae, ay; ddh is commonly confused with dh, d, th, or tth etc. Is it possible to account for all these possible query forms?

Currently yes - but I'm actually in the process of changing this by re-writing the search engine so that adding multiple approximations should be equally fast as well. This is in the works!

> 4. I noticed both the mtd-starter and the web UI will give results which are a “Partial Match” or “Maybe you meant this?”. What is the difference between these two results?

The "Match", "Partial Match" and "Maybe you meant this?" categories basically separate results based on their edit distances, so if you have exact matches either to the word, definition, or compare_form they should turn up in "Match", if you're off by one character, or they satisfy a regex partial match, they should turn up in "Partial Match" and otherwise if you're off by more than one character but fewer than the max edit distance (which I think is typically 2 or 3) then the result ends up in "Maybe you meant this?".

> 5. You mentioned another solution which would allow the NFC to apply to the query was through forking the UI Source. Our plan is that once a working version of the dictionary is built using the mtd-starter, we will add the data to the Web-UI. Will NFC normalization already be applied to the query once we add data to the Web-UI?

The query is whatever someone types in to the search bar, so it has to be normalized at that point (ie at run time). So the change that I mention above for the search code will have to be done in the Web UI as well unfortunately. As part of the new changes that I'm making, I'm refactoring out the search functionality as its own TypeScript package so hopefully these types of changes will be easier to maintain and implement across different UIs.
> 
> Let me know if any of these questions aren’t clear. As always, thank you so much for your help!

**Comment by BaileyTrotter** [comment]
Thanks for these answers! It helped a lot. 

The one thing I am still struggling with is the norm transducer. I've tried to set it up to include each of the vowels which have diacritics (since a lot of community members type with a keyboard which uses combining diacritics and are likely to enter those characters in the query), but it still doesn't seem to be applying to the query. 

For example if I type u/U+0301nzi for the entry únzi instead of U+00FAnzi I'm get a "Maybe you meant this?" result, since it's two characters off from the entry form of U+00FAnzi. 

Do you know if I'm still missing a step to have the norm traducer apply to the query?

**Comment by roedoejet** [comment]
No problem! Did you implement the change above that I described?:

> Unfortunately because of the way this works, you will have to list each transformation, so \u0065\u0301,\u00E9 for example. If you want to actually apply an NFC normalization to the query, you could fork the [UI source](https://github.com/roedoejet/mothertongues-UI) and then change line 66 [here](https://github.com/roedoejet/mothertongues-UI/blob/master/src/pages/search/search.ts) to `let searchQuery = mtd.convertQuery(this.searchQuery).normalize('NFC');` - then run `npm run-script minify` at the root to generate the minified source and commit the changes to the `gh-pages` branch. Then point change line 31 in the [starter index.html](https://github.com/BaileyTrotter/mtd-starter/blob/gh-pages/index.html) to point to your version of the minified UI instead of mine.

In the new version that I'm working on this will all be done for you, so that the normalization that you use on the command line is synchronized automatically with the normalization in the UI. 

Perhaps we could jump on a call sometime in the next couple weeks? We could get to the bottom of this issue, and I could show you the new version that is a work-in-progress, and see if it suits your needs. Just email me with your availability if you'd like to do that! If you're too busy right now, no worries, I'm happy to keep debugging here asynchronously.

**Comment by BaileyTrotter** [comment]
It would be great to jump on a call to work this out, and to see the new version that you are working on. I'll send you an email to figure out timing!

I didn't implement the changes you described. I opted to just list each transformation in the norm transducer file since in the current version of the dictionary we only have about ~10 vowels with diacritics that I'm worried about in the query. Would it be best if I actually went through the process to apply NFC normalization to the query? Right now it looks like the issue might be that it isn't able to create a transducer out of the norm.csv file, but I'm not really sure.
